### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by m0grochowski** [creeperyang/zSlider#1]
Lates version of Google Hrome mobile got issue. Slider appear as white space and jump away from canvas.

Container have height and width set to 100vh and vw. Maybe it is source of problem, but I can't fix that.

Can't explain what heppened i going to put screenshoot
https://drive.google.com/file/d/0B2OVhcBgnu05MEJldVU5UEg3d3M/view?usp=sharing
![screenshot_2015-06-16-08-45-02](https://cloud.githubusercontent.com/assets/12907089/8177405/bb738556-1404-11e5-8c6d-e70d15649ca2.png)

Sory for terrible language.

**Comment by creeperyang** [comment]
@m0grochowski  Sorry for late reply. It looks like a style compatibility issue. Maybe more info about Android version and browser info?
