### ISSUE TITLE
2 item Issue 

### ISSUE THREAD

**Issue by velup** [creeperyang/zSlider#2]
Hi 
The next and previous icon getting overlap when I have only 2 item in the slider.....
can you give the solution for this....

Ya 

My question is When I have only 2 item in the slider in that case the zSlider will clone the two item and clone at the bottom of the slider. which is making issue.

can't we avoid the cloning the items when we have only 2 items..

**Comment by creeperyang** [comment]
Not sure about your problem. 

The `zSlider` plugin itself doesn't offer next and previous icons and it prefer mouse drag or touch move. So the icons you insert may be inserted into wrong place or just your style problem.

A alternative solution: leave icons aside(dont insert into the slider wrap and style them alone), and call `slider.slide('left'|'right')` when click icon.

**Comment by rvaldemar** [comment]
I have the same problem. When have only 2 items, the items overlap and the ones that should be hidden are not.

**Comment by creeperyang** [comment]
If we have only 2 items, currently we will copy DOM elements to support infinite slide.

@rvaldemar  I will check it soon, and You are **welcome** to send a pr to solve the problem.

**Comment by Dhirenmotwani** [comment]
@creeperyang any solution for this?
