### ISSUE TITLE
zslider.min.js bigger then zslider.js?

### ISSUE THREAD

**Issue by futtta** [creeperyang/zSlider#3]
dist/zslider.js is 18KB
dist/zslider.min.js is 30KB

When minimizing dist/zslider.js using http://jscompress.com/, the resulting file is 6KB.

So the question; why is zslider.min.js that big?

**Comment by creeperyang** [comment]
@futtta Thanks for pointing out the ridiculous thing. I'll check it as soon. http://jscompress.com/ is a good util website, but I'll check the `grunt`'s compress plugin first.

**Comment by creeperyang** [comment]
@futtta Seems `grunt-contrib-uglify`'s problem. And now `dist/zSlider.min.js` is `6KB`.

**Comment by futtta** [comment]
thanks @creeperyang, have a nice weekend!
