### ISSUE TITLE
lower-end devices transition doesn't work

### ISSUE THREAD

**Issue by ubeliciousgrace** [creeperyang/zSlider#5]
`transition: transform 0.8s linear` is appended to a DOM element for active carousel images (pre, curr) but I've noticed this particular css doesn't get appended to the style attribute on lower-end Android devices (so far I discovered on 4.4.2, 4.4.4). Higher-end such as Android 6.0 seems fine.

`setTransition` method works fine, but somewhere in `setCompatibleStyle` at 

``` javascript
return function(el, prop, value) {
    el.style[getGoodPropName(prop)] = value;
};
```

fails. Can you please take a look at this?

**Comment by creeperyang** [comment]
@graceeunbekim Maybe I should set value with prefixes (`-webkit-translate3d(x,x,x)`) for lower-end devices.

I will update it.

**Comment by creeperyang** [comment]
`v0.0.3` released, and you can have a try. Let me know if this helps to resolve your issue.

**Comment by ubeliciousgrace** [comment]
@creeperyang  this issue happens on `transition 0.8s linear` not being appended to the `li` dom element. Android 4.4.4 should be able to use the styling correctly without `-webkit-` prefix according to (http://caniuse.com/#feat=css-transitions). I will check tomorrow and update the issue ticket. Really appreciate for the prompt response. By the way I saw you changed the comments in English. 👍

**Comment by creeperyang** [comment]
👌  wait for the result.

**Comment by graceeunbekim** [comment]
@creeperyang  issue is still persistent on Android 4.4.4 Samsung Note 4 
<img width="653" alt="screen shot 2016-08-12 at 9 55 25 am" src="https://cloud.githubusercontent.com/assets/3289082/17630181/16052900-6073-11e6-9be7-b08782715ccb.png">

here we're missing `transition: transform 0.8s linear;' in each z-slider-item; hence, you will not see the smooth transition between pre image and curr image.

**Comment by ubeliciousgrace** [comment]
<img width="235" alt="screen shot 2016-08-12 at 3 12 24 pm" src="https://cloud.githubusercontent.com/assets/3289082/17638510/3dbc2742-609f-11e6-8223-17a371bc41d0.png">
@creeperyang 
we need to add `transition: -webkit-transform 0.8s linear` hence `-webkit-` prefix is required for transform when setting webkit transition. `v.0.0.3` still don't append `-webkit-`. Can you please take a look at it make sure `transition: -webkit-transform 0.8s linear` is added for lower-end devices?

Hence following line is incorrect - `transition` is in style but it's value you're setting needs `-webkit` prefix.

``` javascript
if(prop in style) {
    return {
        prop: prop,
        prefix: ''
    };
```

http://caniuse.com/#search=transform

**Comment by creeperyang** [comment]
Now `v0.0.4` enforce `-webkit-` for css values, so `transition: -webkit-transform 0.8s linear` is added in standard browser (support no prefix css property).

Please have a try.

**Comment by ubeliciousgrace** [comment]
@creeperyang looks like it works so far on the devices I've been developing with. Thanks for the quick update!

I see that you're enforcing `-webkit-` prefix in front, but potentially this issue could be persistent on windows or other browsers.

**Comment by creeperyang** [comment]
👌 I'll close this issue.
